# Generated by Django 2.1.7 on 2019-04-11 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('client_name', models.CharField(max_length=16)),
                ('password', models.CharField(max_length=16)),
                ('email', models.EmailField(max_length=254)),
                ('client_img', models.ImageField(blank=True, null=True, upload_to='client_imgs')),
            ],
        ),
        migrations.CreateModel(
            name='Matchup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Pictures',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('img_address', models.ImageField(upload_to='picture_imgs')),
                ('ima_buget', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tag_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=16)),
                ('password', models.CharField(max_length=16)),
                ('email', models.EmailField(max_length=254)),
                ('user_img', models.ImageField(blank=True, null=True, upload_to='user_imgs')),
            ],
        ),
        migrations.AddField(
            model_name='pictures',
            name='img_tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bs_app.Tag'),
        ),
        migrations.AddField(
            model_name='matchup',
            name='matchup_picture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bs_app.Pictures'),
        ),
        migrations.AddField(
            model_name='matchup',
            name='matchup_tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bs_app.Tag'),
        ),
        migrations.AddField(
            model_name='matchup',
            name='matchup_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bs_app.UserInfo'),
        ),
    ]
