# Generated by Django 2.1.7 on 2019-04-11 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bs_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
