# Generated by Django 2.1.7 on 2019-04-11 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bs_app', '0002_auto_20190411_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pictures',
            name='ima_buget',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pictures',
            name='img_tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bs_app.Tag'),
        ),
    ]
