# Generated by Django 2.1.7 on 2019-04-11 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bs_app', '0004_auto_20190411_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchup',
            name='matchup_picture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bs_app.Pictures', verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='matchup',
            name='matchup_tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bs_app.Tag', verbose_name='标签'),
        ),
        migrations.AlterField(
            model_name='matchup',
            name='matchup_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bs_app.UserInfo', verbose_name='用户'),
        ),
    ]
