# Generated by Django 2.1.7 on 2019-04-11 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bs_app', '0005_auto_20190411_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchup',
            name='matchup_picture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bs_app.Pictures'),
        ),
        migrations.AlterField(
            model_name='matchup',
            name='matchup_tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bs_app.Tag'),
        ),
        migrations.AlterField(
            model_name='matchup',
            name='matchup_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bs_app.UserInfo'),
        ),
    ]
