# Generated by Django 2.1.7 on 2019-04-11 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bs_app', '0006_auto_20190411_2017'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissionPackage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30)),
                ('mission', models.FileField(upload_to='missionpackages')),
                ('budget', models.IntegerField(blank=True, null=True)),
                ('begintime', models.DateTimeField(auto_now_add=True)),
                ('updatetime', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('isfinished', models.BooleanField(default=False)),
            ],
        ),
    ]
