# Generated by Django 2.1.7 on 2019-04-11 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bs_app', '0007_missionpackage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='missionpackage',
            name='username',
        ),
        migrations.AddField(
            model_name='missionpackage',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='bs_app.UserInfo'),
            preserve_default=False,
        ),
    ]
