# Generated by Django 2.1.7 on 2019-04-11 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bs_app', '0008_auto_20190411_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missionpackage',
            name='isfinished',
            field=models.BooleanField(default=False, verbose_name='是否完成'),
        ),
    ]
