# Generated by Django 2.1.7 on 2019-04-11 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bs_app', '0009_auto_20190411_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missionpackage',
            name='begintime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='missionpackage',
            name='budget',
            field=models.IntegerField(blank=True, null=True, verbose_name='价格'),
        ),
        migrations.AlterField(
            model_name='missionpackage',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='介绍'),
        ),
        migrations.AlterField(
            model_name='missionpackage',
            name='updatetime',
            field=models.DateTimeField(auto_now=True, verbose_name='修改时间'),
        ),
    ]
