# Generated by Django 2.1.7 on 2019-04-21 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bs_app', '0010_auto_20190411_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='pictures',
            name='predict_tag',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
