# Generated by Django 2.1.7 on 2019-04-22 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bs_app', '0013_auto_20190421_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='pictures',
            name='mission',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='bs_app.MissionPackage'),
        ),
    ]
