# Generated by Django 2.1.7 on 2019-04-23 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bs_app', '0016_auto_20190422_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missionpackage',
            name='budget',
            field=models.FloatField(blank=True, default=10, null=True, verbose_name='价格'),
        ),
    ]
