# Generated by Django 2.1.7 on 2019-04-23 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bs_app', '0017_auto_20190423_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missionpackage',
            name='begintime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='上传时间'),
        ),
    ]
