# Generated by Django 2.1.7 on 2019-04-23 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bs_app', '0019_missionpackage_pic_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='missionpackage',
            name='total_budget',
            field=models.FloatField(blank=True, null=True, verbose_name='总价'),
        ),
        migrations.AlterField(
            model_name='missionpackage',
            name='budget',
            field=models.FloatField(blank=True, default=10, null=True, verbose_name='单价'),
        ),
    ]
