# Generated by Django 2.1.7 on 2019-04-23 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bs_app', '0020_auto_20190423_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientinfo',
            name='wallet',
            field=models.FloatField(default=100),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='wallet',
            field=models.FloatField(default=0),
        ),
    ]
