# Generated by Django 2.1.7 on 2019-04-24 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bs_app', '0021_auto_20190423_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='pictures',
            name='final_tag',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='最终标签'),
        ),
        migrations.AlterField(
            model_name='pictures',
            name='predict_tag',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='系统标签'),
        ),
    ]
