# Generated by Django 2.1.7 on 2019-04-26 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bs_app', '0022_auto_20190424_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missionpackage',
            name='mission',
            field=models.FileField(upload_to='missionpackages', verbose_name='任务包'),
        ),
        migrations.AlterField(
            model_name='pictures',
            name='img_address',
            field=models.ImageField(upload_to='picture_imgs', verbose_name='图片地址'),
        ),
        migrations.AlterField(
            model_name='pictures',
            name='img_budget',
            field=models.FloatField(blank=True, default=0.01, null=True, verbose_name='单价'),
        ),
        migrations.AlterField(
            model_name='pictures',
            name='img_tag_num',
            field=models.IntegerField(default=0, verbose_name='标记次数'),
        ),
    ]
