# Generated by Django 2.1.7 on 2019-04-26 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bs_app', '0023_auto_20190426_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientinfo',
            name='client_name',
            field=models.CharField(max_length=16, verbose_name='客户名'),
        ),
        migrations.AlterField(
            model_name='clientinfo',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='clientinfo',
            name='wallet',
            field=models.FloatField(default=100, verbose_name='钱包'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag_description',
            field=models.TextField(verbose_name='标签'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='wallet',
            field=models.FloatField(default=0, verbose_name='钱包'),
        ),
    ]
